import { csvParser } from './csv-parser';
import { excelParser } from './excel-parser';


/** Словарь типов MIME для расширений файлов. */
export const mimeTypeDict: Record<string, string> = {
  'txt': 'text/plain',
  'png': 'image/png',
  'bmp': 'image/bmp',
  'jpg': 'image/jpg',
  'jpeg': 'image/jpeg',
  'html': 'text/html',
  'pdf': 'application/pdf',
  'svg': 'image/svg+xml',
  'csv': 'text/csv',
  'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

export const fileParserDict: Record<string, FileParser> = {
  'txt': (data: Blob) => data.text(),
  'csv': csvParser,
  'xlsx': excelParser,
  'docx': (data: Blob) => data.arrayBuffer(),
};

/** Список поддерживаемых расширений для просмотра. */
export const supportedExtensions = new Set(Object.keys(mimeTypeDict));

export const excelIndexedColors = [
  {index: 0, name: 'Black', htmlColor: '#000000'},
  {index: 1, name: 'White', htmlColor: '#FFFFFF'},
  {index: 2, name: 'Red', htmlColor: '#FF0000'},
  {index: 3, name: 'Bright Green', htmlColor: '#00FF00'},
  {index: 4, name: 'Blue', htmlColor: '#0000FF'},
  {index: 5, name: 'Yellow', htmlColor: '#FFFF00'},
  {index: 6, name: 'Pink', htmlColor: '#FF00FF'},
  {index: 7, name: 'Turquoise', htmlColor: '#00FFFF'},
  {index: 8, name: 'Black', htmlColor: '#000000'},
  {index: 9, name: 'White', htmlColor: '#FFFFFF'},
  {index: 10, name: 'Red', htmlColor: '#FF0000'},
  {index: 11, name: 'Bright Green', htmlColor: '#00FF00'},
  {index: 12, name: 'Blue', htmlColor: '#0000FF'},
  {index: 13, name: 'Yellow', htmlColor: '#FFFF00'},
  {index: 14, name: 'Pink', htmlColor: '#FF00FF'},
  {index: 15, name: 'Turquoise', htmlColor: '#00FFFF'},
  {index: 16, name: 'Dark Red', htmlColor: '#800000'},
  {index: 17, name: 'Green', htmlColor: '#008000'},
  {index: 18, name: 'Dark Blue', htmlColor: '#000080'},
  {index: 19, name: 'Dark Yellow', htmlColor: '#808000'},
  {index: 20, name: 'Violet', htmlColor: '#800080'},
  {index: 21, name: 'Teal', htmlColor: '#008080'},
  {index: 22, name: 'Gray-25%', htmlColor: '#C0C0C0'},
  {index: 23, name: 'Gray-50%', htmlColor: '#808080'},
  {index: 24, name: 'Periwinkle', htmlColor: '#9999FF'},
  {index: 25, name: 'Plum', htmlColor: '#993366'},
  {index: 26, name: 'Ivory', htmlColor: '#FFFFCC'},
  {index: 27, name: 'Light Turquoise', htmlColor: '#CCFFFF'},
  {index: 28, name: 'Dark Purple', htmlColor: '#660066'},
  {index: 29, name: 'Coral', htmlColor: '#FF8080'},
  {index: 30, name: 'Ocean Blue', htmlColor: '#0066CC'},
  {index: 31, name: 'Ice Blue', htmlColor: '#CCCCFF'},
  {index: 32, name: 'Dark Blue', htmlColor: '#000080'},
  {index: 33, name: 'Pink', htmlColor: '#FF00FF'},
  {index: 34, name: 'Yellow', htmlColor: '#FFFF00'},
  {index: 35, name: 'Turquoise', htmlColor: '#00FFFF'},
  {index: 36, name: 'Violet', htmlColor: '#800080'},
  {index: 37, name: 'Dark Red', htmlColor: '#800000'},
  {index: 38, name: 'Teal', htmlColor: '#008080'},
  {index: 39, name: 'Blue', htmlColor: '#0000FF'},
  {index: 40, name: 'Sky Blue', htmlColor: '#00CCFF'},
  {index: 41, name: 'Light Turquoise', htmlColor: '#CCFFFF'},
  {index: 42, name: 'Light Green', htmlColor: '#CCFFCC'},
  {index: 43, name: 'Light Yellow', htmlColor: '#FFFF99'},
  {index: 44, name: 'Pale Blue', htmlColor: '#99CCFF'},
  {index: 45, name: 'Rose', htmlColor: '#FF99CC'},
  {index: 46, name: 'Lavender', htmlColor: '#CC99FF'},
  {index: 47, name: 'Tan', htmlColor: '#FFFFCC'},
  {index: 48, name: 'Light Blue', htmlColor: '#3366FF'},
  {index: 49, name: 'Aqua', htmlColor: '#33CCCC'},
  {index: 50, name: 'Lime', htmlColor: '#99CC00'},
  {index: 51, name: 'Gold', htmlColor: '#FFCC00'},
  {index: 52, name: 'Light Orange', htmlColor: '#FF9900'},
  {index: 53, name: 'Orange', htmlColor: '#FF6600'},
  {index: 54, name: 'Blue-Gray', htmlColor: '#666699'},
  {index: 55, name: 'Gray-Gray40%', htmlColor: '#969696'},
  {index: 56, name: 'Dark Teal', htmlColor: '#003366'},
  {index: 57, name: 'Sea Green', htmlColor: '#339966'},
  {index: 58, name: 'Dark Green', htmlColor: '#003300'},
  {index: 59, name: 'Olive Green', htmlColor: '#333300'},
  {index: 60, name: 'Brown', htmlColor: '#993300'},
  {index: 61, name: 'Plum', htmlColor: '#993366'},
  {index: 62, name: 'Indigo', htmlColor: '#333399'},
  {index: 63, name: 'Gray-80%', htmlColor: '#333333'},
];
